# Generated by Django 5.1.1 on 2024-11-27 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heladeria', '0004_categoria_remove_proveedor_categoriasuministrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Categoria',
            new_name='CategoriaPr',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='categoriaPr',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='categoria',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='categoriaProv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='heladeria.categoriaprov'),
        ),
    ]
