# Generated by Django 5.1.1 on 2024-12-13 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heladeria', '0006_producto_costo_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedidoProducto', models.CharField(max_length=30)),
                ('fechaPedido', models.DateField()),
                ('fechaEntrega', models.DateField()),
                ('nombreProveedorPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proovedores', to='heladeria.proveedor')),
            ],
        ),
    ]
